import Head from "next/head";
import Link from "next/link";
import styles from "@/styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>PopTV Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/nanotechnology.png" />
      </Head>
      <nav className={styles.navbar}>
        <Link href="/">
          <h1 className={styles.logo}>
            <span className={styles.pop}>Pop</span>
            <span className={styles.tv}>TV</span>
            <span className={styles.fist}>&#x1f3a4;</span>
          </h1>
        </Link>
        <ul className={styles.navline}>
          <li className={styles.navItem}>
            <Link href="#about" className={styles.navLink} id="nav-link">
              About
            </Link>
          </li>
          <li className={styles.navItem}>
            <Link href="#stars" className={styles.navLink} id="nav-link">
              Pop Stars
            </Link>
          </li>
          <li className={styles.navItem}>
            <Link href="#stakeholders" className={styles.navLink} id="nav-link">
              stakeholders
            </Link>
          </li>
          <li className={styles.navItem}>
            <Link href="#sub" className={styles.navLink} id="nav-link">
              Subscribe
            </Link>
          </li>
        </ul>
        <div className={styles.hamburger} id="hamburger">
          <span className="bar"></span>
          <span className="bar"></span>
          <span className="bar"></span>
        </div>
      </nav>
      <main>
        <section className={styles.hero}>
          <div className="intro-text">
            <h1>
              <span className="hear">You can hear the notes</span>
              <br />
              <span className="connecting">Connecting</span>
            </h1>
            <p>
              An online streaming platform for boxing matches <br />
              We also dedicate some special time to throwbacks cuz old is gold
            </p>
            <Link href="/" className="btn red">
              Learn More
            </Link>
            <Link href="/" className="btn blue">
              Subscribe
            </Link>
          </div>
          <div className="i-frame">
            <iframe
              width={560}
              height={315}
              src="https://music.youtube.com/watch?v=JTxhmZTG72o&feature=share"
              title="Youtube Music Favorite Track of Wk3"
              frameBorder={10}
              allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
            ></iframe>
            <div className="stand-1"></div>
            <div className="stand-2"></div>
          </div>
        </section>
        <section className="about" id="about">
          <h3>Watch the Notes</h3>
          <p>
            Our primary objective is to bring live boxing matches to fans all
            around the world
          </p>

          <h3>Its not about Sing Alone!</h3>
          <p>
            We also air documentaries specially made for the greats, lifestyle
            of boxers, news, and more.
          </p>
        </section>
      </main>
    </>
  );
}
